VAGRANTFILE_API_VERSION = "2"
N_NODES = 3

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  (1..N_NODES).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = 'bento/ubuntu-18.04'

      node.vm.hostname = "node#{i}"

      node.vm.network :private_network, ip: "10.10.10.#{20 + i}0"

      if i == N_NODES
        node.vm.provision :ansible do |ansible|
          ansible.limit = 'all'
          ansible.compatibility_mode = '2.0'
          ansible.playbook = 'playbooks/site.yml'
        end
      end

    end

  end

end
